import os
import sys

from from_root import from_root

p = from_root('CONTRIBUTING.md').parent
sys.path.insert(1, str(p))

from utils.pdf.list_pdf_scrapers import list_pdf_v3

# This script was generated by the setup gui
configs = {
    "webpage":"https://acworthpolice.org/departments/annual-report",
    "web_path":"/images/annualreport/",
    "domain_included":False,
    "domain":"https://acworthpolice.org",
    "sleep_time": 5,
    "non_important":['emergency', ' training', ' guidelines'],
    "debug": False,
    "csv_dir": "/csv/",
}

save_dir = "./data/annual_reports/"

list_pdf_v3(configs, save_dir)
