# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/error_modal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error_dialog(object):
    def setupUi(self, error_dialog):
        error_dialog.setObjectName("error_dialog")
        error_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        error_dialog.resize(400, 300)
        error_dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(error_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(error_dialog)
        self.label.setGeometry(QtCore.QRect(70, 90, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(error_dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(error_dialog)
        self.buttonBox.accepted.connect(error_dialog.accept)
        self.buttonBox.rejected.connect(error_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(error_dialog)

    def retranslateUi(self, error_dialog):
        _translate = QtCore.QCoreApplication.translate
        error_dialog.setWindowTitle(_translate("error_dialog", "Dialog"))
        self.label.setText(_translate("error_dialog", "You need to complete the first menu first"))
        self.label_2.setText(_translate("error_dialog", "ERROR:"))
