import sys
import os
from pathlib import Path

p = Path(__file__).resolve().parents[5]
sys.path.insert(1, str(p))
from common import list_pdf_v2

# This script was generated by the setup gui
configs = {
    "webpage": "",
    "web_path": "",
    "domain_included": False,
    "domain": "",
    "sleep_time": 5,
    "debug": False,
    "csv_dir": "/csv/",
}

save_dir = "./data/"

list_pdf_v2(configs, save_dir)
